receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - ${FRONTEND_URL}
processors:
  batch:

exporters:
  otlp:
    endpoint: "${OTEL_EXPORTER_OTLP_URL}"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
  logging:
    loglevel: debug
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]